<?php
/*
	This file contains default functions and values for all pages.
	DO NOT EDIT THIS FILE.
	If you would like to change a default value, override it in a 
	different php file, and record that file location below.
*/
$my_page_defaults = "my_page_defaults.php";

$links_loc = "/home/user/public_html/hidden/banner/links.php";
$alias = "/OpenRPG";
$authdir = "../hidden/auth";
$sess_name = "OpenRPG";

include($my_page_defaults);


// FUNCTIONS:

function auth_check($alias, $type) {

	if(!isset($_SESSION)) {
		header("Location: $alias/login_manager.php?a=login");
		exit;

	} else if(!isset($_SESSION['logged_in'])) {
		$_SESSION['curr_page'] = $_SERVER['REQUEST_URI'];
		header("Location: $alias/login_manager.php?a=login");

	} else if(!isset($_SESSION['verified'])) {
		$_SESSION['curr_page'] = $_SERVER['REQUEST_URI'];
		header("Location: $alias/login_manager.php?a=verify");
	}

	// Authorize for admin pages.
	if($type == "admin" && !isset($_SESSION["admin"])) {
		header("Location: $alias/index.php");
	}
}

function open_html($add) {
	echo <<<EOT
	<html>
	<head>
		$add
		<title>Open RPG</title>
		<link rel="stylesheet" type="text/css" href="/OpenRPG_styles/global.css">
	</head>
	<body>
		<div class="main">
EOT;

}

function disp_banner($p, $links_loc, $alias) {
	include($links_loc);
	$user = $_SESSION['user'];
	$prct = round((100/count($blinks)), 1);
	echo <<<EOT
			<table width=100%>
			<tr>
				<td width=33.3%>
				<br />
					<p class="banner" style="text-align:left;"><a href="/">Home</a></p>
				</td>
				<td width=33.3%>
					<h1 style="text-align:center">Open RPG</h1>
				</td>
				<td width=33.3%>
					<br />
					<p class="banner">Logged in as: $user<br />
					<a href="/OpenRPG/login_manager.php?a=logout">Log out</a> | <a href="/OpenRPG/login_manager.php?a=switch">Switch user</a></p>
				</td>
			</tr>
			</table>
			<table width="100%" class="nav">
			<tr>
EOT;
	foreach($blinks as $k => $v) {
		echo "<td width=\"$prct%\"";
		if(isset($p)) {
			if($k == $p) {
			echo " class=\"selected\"";
			}
		}
		echo "><a href=\"$alias$v[1]\">$v[0]</a></td>";
	}
	echo "</tr></table><hr />";

}

function close_html() {
	echo "</div></body></html>";
}

?>
